#!/bin/sh

# dir name to use is passed in argument
output=$1

cat <<EOF
added lines per line = $output/added-per-line.svg
api calls = $output/API-calls-over-time.svg
atoi density = $output/atoi-over-time.svg
author activity = $output/authors-active.svg
author density = $output/remains-per-kloc.svg
authors = $output/authors.svg
authors of 50 percent = $output/50-percent.svg
authors of 60 percent = $output/60-percent.svg
authors of 70 percent = $output/70-percent.svg
authors of 80 percent = $output/80-percent.svg
authors of 90 percent = $output/90-percent.svg
authors of 95 percent = $output/95-percent.svg
authors per kloc = $output/lines-per-author.svg
authors per month = $output/authors-per-month.svg
authors per year = $output/authors-per-year.svg
authors remaining = $output/authorremains.svg
authors remaining toplist = $output/authorremains-top.svg
authors top-40 = $output/top-remains.svg
authors who are first timers = $output/firsttimers.svg
backends = $output/backends-over-time.svg
bug bounty = $output/bugbounty-over-time.svg
bug bounty amounts = $output/bugbounty-amounts.svg
bugfix frequency = $output/bugfix-frequency.svg
c mistakes = $output/c-vuln-code.svg
c vulnerability share = $output/c-vuln-reports.svg
cmdline options over time = $output/cmdline-options-over-time.svg
comments in source code = $output/comments.svg
commit size distribution = $output/commit-sizes.svg
commits = $output/commits-over-time.svg
commits by Daniel = $output/daniel-commit-share.svg
commits monthly = $output/month-of-year.svg
commits per day = $output/date-of-year.svg
commits per month = $output/commits-per-month.svg
commits per release = $output/commits-per-release.svg
commits per year = $output/commits-per-year.svg
commits weekly = $output/weekday-of-year.svg
complexity = $output/complexity.svg
complexity averarge = $output/line-complex.svg
complexity distribution = $output/complex-dist.svg
contribution tail = $output/contrib-tail.svg
contributors = $output/contributors-over-time.svg
contributors per release = $output/contributors-per-release.svg
coreteam per year = $output/coreteam-per-year.svg
curl man page size = $output/manpage.svg
curl man size per option = $output/manpage-lines-per-option.svg
CWE top = $output/top-cwe.svg
Daniel vs rest = $output/daniel-vs-rest.svg
documentation = $output/docs-over-time.svg
documentation per kloc = $output/lines-per-docs.svg
examples = $output/examples-over-time.svg
file size = $output/filesize-over-time.svg
files = $output/files-over-time.svg
function length = $output/funclen.svg
github age = $output/gh-age.svg
github fixes = $output/gh-fixes.svg
github monthly = $output/gh-monthly.svg
github open = $output/gh-open.svg
graphs on the dashboard = $output/graphs.svg
hackerone = $output/h1-per-year.svg
http versions = $output/http-over-time.svg
ifdef density = $output/ifdef-over-time.svg
lines added = $output/lines-person.svg
mail = $output/mail.svg
man pages = $output/manpages-over-time.svg
memory function density = $output/cpy-over-time.svg
memory spend for downloading 512 mb = $output/512-mb.svg
project age = $output/project-age.svg
protocols = $output/protocols-over-time.svg
release frequency = $output/days-per-release.svg
releases = $output/release-number.svg
releases per year = $output/releases-per-year.svg
setopts = $output/setopts-over-time.svg
size of connectdata = $output/connectdata.svg
size of easy handle = $output/easy-handle.svg
size of multi handle = $output/multi-handle.svg
source code age = $output/codeage.svg
source code delta = $output/lines-per-month.svg
source code lines = $output/lines-over-time.svg
source code lines per day = $output/loc-per-day.svg
sscanf density = $output/sscanf-over-time.svg
strcpy density = $output/strcpy-over-time.svg
strncpy density = $output/strncpy-over-time.svg
symbols = $output/symbols-over-time.svg
test infrastructure lines = $output/testinfra-over-time.svg
test infrastructure per kloc = $output/testinfra-per-line.svg
test infrastructure per test = $output/testinfra-per-test.svg
tests = $output/tests-over-time.svg
tests per kloc = $output/lines-per-test.svg
third parties = $output/3rdparty-over-time.svg
time zone use in commits = $output/timezones.svg
todo = $output/todo-over-time.svg
vulnerabilities in releases = $output/vulns-releases.svg
vulnerabilities in code = $output/vuln-dist-code.svg
vulnerabilities per kloc = $output/knownvulns-per-line.svg
vulnerabilities per time = $output/vulns-over-time.svg
vulnerabilities per year = $output/vulns-per-year.svg
vulnerability age = $output/cve-age.svg
vulnerability high vs low = $output/sev-per-year.svg
vulnerability severity = $output/high-vuln-reports.svg
vulnerability severity distribution = $output/severity.svg
vulnerability share = $output/cve-pie-chart.svg
vulnerability time to fix = $output/cve-fixtime.svg
EOF
